//! 1D digital waveguide network for engine intake and induction acoustics.
//!
//! # Intake acoustics
//!
//! Sound in the induction tract travels through digital waveguides:
//! bidirectional delay lines carrying forward-travelling pressure waves $p^+$
//! (toward the atmosphere / mouth) and backward-travelling pressure waves $p^-$
//! (toward the intake valves).
//!
//! Topology:
//! ```text
//! intake valve -> port -> runner -> plenum junction (N runners) -> throttle
//!     -> airbox -> snorkel -> mouth radiation -> listener
//! ```
//!
//! For engines fitted with individual throttle bodies (ITBs), the runners vent
//! directly to atmosphere through velocity stack mouths with no shared plenum.
//!
//! Processing runs in `f32` at the audio sample rate with zero allocation
//! in the audio callback.

use crate::audio::filters::speed_of_sound;
use crate::audio::radiation::Mouth;
use crate::audio::waveguide::{ScatteringJunction, ValveTermination, WaveguidePipe};
use crate::physics::plumbing::{IntakeSystem, ThrottleLayout};

/// Reference ambient temperature for intake air [K].
pub const INTAKE_AMBIENT_TEMPERATURE_K: f32 = 300.0;

/// Specific heat ratio of fresh air [-].
pub const INTAKE_AIR_GAMMA: f32 = 1.40;

/// Specific gas constant of fresh air [J/(kg K)].
pub const INTAKE_GAS_CONSTANT: f32 = 287.0;

/// Induction rarefaction acoustic pressure pulse at valve opening [Pa]:
///
/// $$p' = -\rho c u = -\frac{c \dot{m}}{A}$$
///
/// As the piston descends with the intake valve open, it pulls air into the cylinder,
/// launching a negative pressure (rarefaction) wave up the runner toward the mouth.
#[inline]
pub fn induction_rarefaction_pa(mass_flow: f32, runner_area: f32, speed_of_sound: f32) -> f32 {
    if runner_area <= 1e-7 {
        0.0
    } else {
        -speed_of_sound * mass_flow.max(0.0) / runner_area
    }
}

/// Acoustic water hammer pressure pulse from intake valve closing slam [Pa]:
///
/// $$\Delta p_{\text{slam}} = \frac{L}{A} \max\left(0, -\frac{d\dot{m}}{dt}\right)$$
///
/// At intake valve closing (IVC), the inertia of the moving air column in the runner
/// slams into the shutting valve, converting kinetic energy into a sharp positive
/// pressure wavefront that travels up the runner and radiates from the mouth.
#[inline]
pub fn valve_slam_pa(d_mdot_dt: f32, runner_length: f32, runner_area: f32) -> f32 {
    if runner_area <= 1e-7 {
        0.0
    } else {
        (runner_length.max(0.0) / runner_area) * (-d_mdot_dt).max(0.0)
    }
}

/// Dipole orifice noise amplitude scaling from normalized flow velocity [-]:
///
/// $$p_{\text{rms}} \propto u^3$$
///
/// Aeroacoustic dipole sound generated by turbulent flow through an orifice radiates
/// acoustic power scaling with the sixth power of velocity ($W \propto u^6$).
/// The corresponding acoustic pressure amplitude scales with the cube of velocity ($u^3$).
#[inline]
pub fn dipole_orifice_amplitude(flow_ratio: f32) -> f32 {
    let u = flow_ratio.max(0.0);
    u * u * u
}

/// Calculates the geometric open area of a throttle body [m^2] from pedal position `0..=1`.
///
/// Follows the physical throttle plate geometry:
/// $$A_{\text{open}}(\theta) = A_{\text{bore}} \cdot \left[1 - \cos\left(\theta \frac{\pi}{2}\right)\right] + A_{\text{leak}}$$
/// where $A_{\text{leak}} = 0.008 \cdot A_{\text{bore}}$ represents idle bypass and edge leakage.
#[inline]
pub fn throttle_area(bore_diameter: f64, throttle_position: f32) -> f32 {
    let t = (throttle_position as f64).clamp(0.0, 1.0);
    let radius = bore_diameter.max(1e-4) * 0.5;
    let bore_area = std::f64::consts::PI * radius * radius;
    let leak_area = bore_area * 0.008;
    let swept_area = bore_area * (1.0 - (t * std::f64::consts::FRAC_PI_2).cos());
    ((swept_area + leak_area).min(bore_area)) as f32
}

/// Computes acoustic scattering across a throttle area restriction $A_{\text{th}}$.
///
/// Models an orifice of area $A_{\text{th}}$ connecting duct 1 ($A_1$) and duct 2 ($A_2$).
/// Acoustic series resistance of the restriction:
///
/// $$Z_{\text{rest}} = \max\left(0, \frac{1}{A_{\text{th}}} - \frac{1}{\min(A_1, A_2)}\right)$$
///
/// Acoustic volume velocity through the restriction:
///
/// $$U = \frac{2 (p_1^+ - p_2^+)}{\frac{1}{A_1} + \frac{1}{A_2} + 2 Z_{\text{rest}}}$$
///
/// Scattered waves returning into each duct:
///
/// $$p_1^- = p_1^+ - \frac{U}{A_1}$$
/// $$p_2^- = p_2^+ + \frac{U}{A_2}$$
///
/// When the throttle is shut ($A_{\text{th}} \approx A_{\text{leak}} \to 0$), $Z_{\text{rest}} \to \infty$,
/// driving $U \to 0$, $p_1^- \to p_1^+$, $p_2^- \to p_2^+$ (rigid reflections, transmission vanishes).
/// When wide open ($A_{\text{th}} \ge \min(A_1, A_2)$), $Z_{\text{rest}} = 0$, giving unimpeded transmission.
#[inline]
pub fn scatter_throttle_restriction(
    p1_plus: f32,
    p2_plus: f32,
    area1: f32,
    area2: f32,
    throttle_area: f32,
) -> (f32, f32) {
    let a1 = area1.max(1e-7);
    let a2 = area2.max(1e-7);
    let a_th = throttle_area.max(1e-9);
    let min_a = a1.min(a2);
    let z_rest = (1.0 / a_th - 1.0 / min_a).max(0.0);
    let denom = (1.0 / a1) + (1.0 / a2) + 2.0 * z_rest;
    let u = (2.0 * (p1_plus - p2_plus)) / denom;
    let p1_minus = p1_plus - (u / a1);
    let p2_minus = p2_plus + (u / a2);
    (p1_minus, p2_minus)
}

/// 1D digital waveguide network representing the complete intake system.
#[derive(Debug, Clone)]
pub struct IntakeNetwork {
    /// Intake runners (one per cylinder).
    runners: Vec<WaveguidePipe>,
    /// Valve boundary conditions at the cylinder ports.
    valves: Vec<ValveTermination>,
    /// Junction where all runners meet the central plenum cavity.
    plenum_junction: Option<ScatteringJunction>,
    /// Central plenum cavity duct.
    plenum_pipe: Option<WaveguidePipe>,
    /// Upstream airbox duct, if fitted.
    airbox_pipe: Option<WaveguidePipe>,
    /// Air inlet snorkel duct, if fitted.
    snorkel_pipe: Option<WaveguidePipe>,
    /// Mouth radiation termination for single-throttle systems.
    single_mouth: Option<Mouth>,
    /// Mouth radiation terminations for ITB systems (one per runner).
    itb_mouths: Vec<Mouth>,

    // Preallocated buffers for real-time processing
    runner_in_0: Vec<f32>,
    runner_to_plenum: Vec<f32>,
    plenum_scatter_in: Vec<f32>,
    plenum_scatter_out: Vec<f32>,
    plenum_to_downstream: f32,
    downstream_to_plenum: f32,
    itb_mouth_refl: Vec<f32>,

    /// Number of cylinders.
    cylinder_count: usize,
    /// Sample rate [Hz].
    sample_rate: f32,
    /// Current throttle position, `0..=1` [-].
    throttle: f32,
    /// Throttle bore diameter [m].
    throttle_bore: f64,
    /// Plenum cavity cross-sectional area [m^2].
    plenum_area: f32,
    /// Downstream duct cross-sectional area [m^2].
    downstream_area: f32,
    /// Throttle arrangement and geometry.
    layout: ThrottleLayout,
}

impl IntakeNetwork {
    /// Constructs a new intake waveguide network from an [`IntakeSystem`] description.
    pub fn new(intake: &IntakeSystem, cylinder_count: usize, sample_rate: f32) -> Self {
        let n_cyl = cylinder_count.max(1);
        let gamma = INTAKE_AIR_GAMMA;
        let r = INTAKE_GAS_CONSTANT;
        let temp = INTAKE_AMBIENT_TEMPERATURE_K;
        let c = speed_of_sound(gamma, r, temp);

        let is_itb = matches!(intake.throttle, ThrottleLayout::IndividualBodies { .. });

        // 1. Runners and valve terminations
        let mut runners = Vec::with_capacity(n_cyl);
        let mut valves = Vec::with_capacity(n_cyl);
        let mut itb_mouths = Vec::with_capacity(if is_itb { n_cyl } else { 0 });

        for i in 0..n_cyl {
            let spec = if !intake.runners.is_empty() {
                intake.runners[i % intake.runners.len()]
            } else {
                crate::physics::plumbing::PipeSection::from_diameter(0.30, 0.042, 310.0)
            };

            if is_itb {
                let radius = (spec.area / std::f64::consts::PI).sqrt() as f32;
                let mouth = Mouth::new(sample_rate, radius, intake.trumpet_flanged, c);
                let eff_len = spec.length + mouth.end_correction() as f64;
                let mut pipe = WaveguidePipe::new(eff_len, spec.area, sample_rate, gamma, r, temp);
                pipe.set_boundary_phase_delay(mouth.phase_delay_samples());
                runners.push(pipe);
                itb_mouths.push(mouth);
            } else {
                let pipe = WaveguidePipe::new(spec.length, spec.area, sample_rate, gamma, r, temp);
                runners.push(pipe);
            }
            valves.push(ValveTermination::new(spec.area));
        }

        // 2. Single throttle path (plenum, airbox, snorkel, mouth)
        let (plenum_junction, plenum_pipe, airbox_pipe, snorkel_pipe, single_mouth) = if is_itb {
            (None, None, None, None, None)
        } else {
            // Plenum cavity: length 0.20 m, area = volume / length
            let plenum_len = 0.20f64;
            let plenum_area = (intake.plenum_volume / plenum_len).max(1e-5);
            let plenum_pipe =
                WaveguidePipe::new(plenum_len, plenum_area, sample_rate, gamma, r, temp);

            // Scattering junction: N runners + 1 plenum pipe
            let mut junction_areas = Vec::with_capacity(n_cyl + 1);
            for r in &runners {
                junction_areas.push(r.area() as f64);
            }
            junction_areas.push(plenum_area);
            let plenum_junction = ScatteringJunction::from_areas(&junction_areas);

            // Airbox
            let airbox_pipe = intake.airbox.map(|box_spec| {
                WaveguidePipe::new(box_spec.length, box_spec.area, sample_rate, gamma, r, temp)
            });

            // Snorkel
            let snorkel_pipe = intake.snorkel.map(|snork_spec| {
                WaveguidePipe::new(
                    snork_spec.length,
                    snork_spec.area,
                    sample_rate,
                    gamma,
                    r,
                    temp,
                )
            });

            // Exit mouth
            let exit_spec = intake.snorkel.or(intake.airbox).unwrap_or_else(|| {
                crate::physics::plumbing::PipeSection::from_diameter(0.20, 0.070, 300.0)
            });
            let mouth_radius = (exit_spec.area / std::f64::consts::PI).sqrt() as f32;
            let mouth = Mouth::new(sample_rate, mouth_radius, intake.trumpet_flanged, c);

            (
                Some(plenum_junction),
                Some(plenum_pipe),
                airbox_pipe,
                snorkel_pipe,
                Some(mouth),
            )
        };

        let runner_in_0 = vec![0.0; n_cyl];
        let runner_to_plenum = vec![0.0; n_cyl];
        let plenum_scatter_in = vec![0.0; n_cyl + 1];
        let plenum_scatter_out = vec![0.0; n_cyl + 1];
        let itb_mouth_refl = vec![0.0; if is_itb { n_cyl } else { 0 }];

        let throttle_bore = match intake.throttle {
            ThrottleLayout::Single { bore } => bore,
            ThrottleLayout::IndividualBodies { bore } => bore,
        };
        let plenum_len = 0.20f64;
        let plenum_area = if is_itb {
            0.0
        } else {
            (intake.plenum_volume / plenum_len).max(1e-5) as f32
        };
        let downstream_area = if is_itb {
            0.0
        } else {
            intake
                .airbox
                .or(intake.snorkel)
                .map(|s| s.area as f32)
                .unwrap_or(0.00385)
        };

        Self {
            runners,
            valves,
            plenum_junction,
            plenum_pipe,
            airbox_pipe,
            snorkel_pipe,
            single_mouth,
            itb_mouths,
            runner_in_0,
            runner_to_plenum,
            plenum_scatter_in,
            plenum_scatter_out,
            plenum_to_downstream: 0.0,
            downstream_to_plenum: 0.0,
            itb_mouth_refl,
            cylinder_count: n_cyl,
            sample_rate,
            throttle: 0.0,
            throttle_bore,
            plenum_area,
            downstream_area,
            layout: intake.throttle,
        }
    }

    /// Retunes propagation delays and losses for current gas state.
    pub fn tune(&mut self, gamma: f32, gas_constant: f32, temperature: f32) {
        let c = speed_of_sound(gamma, gas_constant, temperature);
        for p in &mut self.runners {
            p.tune(gamma, gas_constant, temperature);
        }
        if let Some(p) = &mut self.plenum_pipe {
            p.tune(gamma, gas_constant, temperature);
        }
        if let Some(p) = &mut self.airbox_pipe {
            p.tune(gamma, gas_constant, temperature);
        }
        if let Some(p) = &mut self.snorkel_pipe {
            p.tune(gamma, gas_constant, temperature);
        }
        if let Some(m) = &mut self.single_mouth {
            m.tune(c);
        }
        for m in &mut self.itb_mouths {
            m.tune(c);
        }
    }

    /// Updates valve effective flow areas for all cylinders.
    pub fn set_valve_areas(&mut self, valve_areas: &[f64]) {
        for (v, &area) in self.valves.iter_mut().zip(valve_areas.iter()) {
            v.set_effective_area(area);
        }
    }

    /// Updates the throttle position, `0.0..=1.0` [-].
    pub fn set_throttle(&mut self, throttle: f32) {
        self.throttle = throttle.clamp(0.0, 1.0);
    }

    /// Number of cylinders in this intake system.
    pub fn cylinder_count(&self) -> usize {
        self.cylinder_count
    }

    /// Audio sample rate [Hz].
    pub fn sample_rate(&self) -> f32 {
        self.sample_rate
    }

    /// Throttle arrangement and geometry.
    pub fn layout(&self) -> &ThrottleLayout {
        &self.layout
    }

    /// Steps the intake waveguide network by one audio sample.
    ///
    /// - `excitations`: slice of acoustic pressure excitations per cylinder [Pa].
    ///
    /// Returns the radiated acoustic pressure [Pa].
    #[inline(always)]
    pub fn step(&mut self, excitations: &[f32]) -> f32 {
        let n_cyl = self.runners.len();

        if !self.itb_mouths.is_empty() {
            // Individual throttle bodies (ITBs)
            let a_th = throttle_area(self.throttle_bore, self.throttle);
            let mut total_rad = 0.0f32;
            for i in 0..n_cyl {
                let (p_at_valve, p_at_mouth) = self.runners[i].read_outputs();
                let excit = if i < excitations.len() {
                    excitations[i]
                } else {
                    0.0
                };
                let p_in_valve = self.valves[i].step(excit, p_at_valve);
                let runner_area = self.runners[i].area();
                let prev_refl = self.itb_mouth_refl[i];
                let (p_back_to_runner, p_to_mouth) = scatter_throttle_restriction(
                    p_at_mouth,
                    prev_refl,
                    runner_area,
                    runner_area,
                    a_th,
                );
                let (new_refl, p_rad) = self.itb_mouths[i].step(p_to_mouth);
                self.itb_mouth_refl[i] = new_refl;
                self.runners[i].push_inputs(p_in_valve, p_back_to_runner);
                total_rad += p_rad;
            }
            total_rad / (n_cyl as f32).sqrt().max(1.0)
        } else {
            // Single throttle with plenum
            // 1. Read runner outputs at valve and plenum boundaries
            for i in 0..n_cyl {
                let (p_at_valve, p_at_plenum) = self.runners[i].read_outputs();
                let excit = if i < excitations.len() {
                    excitations[i]
                } else {
                    0.0
                };
                self.runner_in_0[i] = self.valves[i].step(excit, p_at_valve);
                self.runner_to_plenum[i] = p_at_plenum;
            }

            // 2. Read plenum cavity outputs
            let (p_plenum_at_runners, p_plenum_at_exit) = match &mut self.plenum_pipe {
                Some(p) => p.read_outputs(),
                None => (0.0, 0.0),
            };

            // 3. Scatter at plenum junction: N runners + plenum cavity
            if let Some(junc) = &self.plenum_junction {
                for i in 0..n_cyl {
                    self.plenum_scatter_in[i] = self.runner_to_plenum[i];
                }
                self.plenum_scatter_in[n_cyl] = p_plenum_at_runners;

                junc.scatter(&self.plenum_scatter_in, &mut self.plenum_scatter_out);

                for i in 0..n_cyl {
                    let p_back_to_runner = self.plenum_scatter_out[i];
                    self.runners[i].push_inputs(self.runner_in_0[i], p_back_to_runner);
                }
            }

            // 4. Scatter through throttle restriction between plenum exit and downstream duct
            let a_th = throttle_area(self.throttle_bore, self.throttle);
            let (p_back_to_plenum, p_to_downstream) = scatter_throttle_restriction(
                p_plenum_at_exit,
                self.downstream_to_plenum,
                self.plenum_area,
                self.downstream_area,
                a_th,
            );

            // 5. Downstream chain: airbox -> snorkel -> mouth
            let mut wave_forward = p_to_downstream;
            let mut wave_backward = 0.0f32;

            if let Some(airbox) = &mut self.airbox_pipe {
                let (p_box_in, p_box_out) = airbox.read_outputs();
                airbox.push_inputs(wave_forward, self.downstream_to_plenum);
                wave_forward = p_box_out;
                wave_backward = p_box_in;
            }

            if let Some(snorkel) = &mut self.snorkel_pipe {
                let (p_snork_in, p_snork_out) = snorkel.read_outputs();
                snorkel.push_inputs(wave_forward, self.downstream_to_plenum);
                wave_forward = p_snork_out;
                wave_backward = p_snork_in;
            }

            let radiated = if let Some(mouth) = &mut self.single_mouth {
                let (refl, rad) = mouth.step(wave_forward);
                self.downstream_to_plenum =
                    if self.snorkel_pipe.is_some() || self.airbox_pipe.is_some() {
                        wave_backward
                    } else {
                        refl
                    };
                rad
            } else {
                0.0
            };

            let p_into_plenum_0 = self.plenum_scatter_out[n_cyl];
            if let Some(plenum) = &mut self.plenum_pipe {
                plenum.push_inputs(p_into_plenum_0, p_back_to_plenum);
            }

            radiated
        }
    }

    /// Resets all internal delay lines and filters.
    pub fn reset(&mut self) {
        for r in &mut self.runners {
            r.reset();
        }
        for v in &mut self.valves {
            v.set_effective_area(0.0);
        }
        if let Some(p) = &mut self.plenum_pipe {
            p.reset();
        }
        if let Some(p) = &mut self.airbox_pipe {
            p.reset();
        }
        if let Some(p) = &mut self.snorkel_pipe {
            p.reset();
        }
        if let Some(m) = &mut self.single_mouth {
            m.reset();
        }
        for m in &mut self.itb_mouths {
            m.reset();
        }
        self.runner_in_0.fill(0.0);
        self.runner_to_plenum.fill(0.0);
        self.plenum_scatter_in.fill(0.0);
        self.plenum_scatter_out.fill(0.0);
        self.plenum_to_downstream = 0.0;
        self.downstream_to_plenum = 0.0;
        self.itb_mouth_refl.fill(0.0);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn intake_network_constructs_and_runs_stable() {
        let system = IntakeSystem::default_for_cylinders(4);
        let mut network = IntakeNetwork::new(&system, 4, 48_000.0);
        network.tune(
            INTAKE_AIR_GAMMA,
            INTAKE_GAS_CONSTANT,
            INTAKE_AMBIENT_TEMPERATURE_K,
        );

        let excitations = [100.0, 0.0, 0.0, 0.0];
        for _ in 0..1000 {
            let rad = network.step(&excitations);
            assert!(rad.is_finite());
        }
    }

    #[test]
    fn induction_rarefaction_matches_physical_formula() {
        let mdot = 0.045f32;
        let area = 0.0015f32;
        let c = 340.0f32;
        let p_prime = induction_rarefaction_pa(mdot, area, c);
        assert!((p_prime - (-c * mdot / area)).abs() < 1e-4);
        assert!(p_prime < 0.0, "rarefaction must be negative pressure");

        // Zero mass flow produces no pressure pulse
        assert_eq!(induction_rarefaction_pa(0.0, area, c), 0.0);
    }

    #[test]
    fn valve_slam_scales_with_flow_derivative_and_runner_length() {
        let d_mdot = -15.0f32;
        let l1 = 0.25f32;
        let l2 = 0.50f32;
        let area = 0.0014f32;

        let p1 = valve_slam_pa(d_mdot, l1, area);
        let p2 = valve_slam_pa(d_mdot, l2, area);

        assert!(
            p1 > 0.0,
            "water hammer slam must be a positive pressure surge"
        );
        assert!(
            (p2 - 2.0 * p1).abs() < 1e-4,
            "doubling runner length must double water hammer amplitude"
        );

        let p_double_derivative = valve_slam_pa(2.0 * d_mdot, l1, area);
        assert!(
            (p_double_derivative - 2.0 * p1).abs() < 1e-4,
            "doubling flow shutoff rate must double water hammer amplitude"
        );

        // Opening valve (flow increasing) produces zero slam pulse
        assert_eq!(valve_slam_pa(15.0, l1, area), 0.0);
    }

    #[test]
    fn dipole_orifice_noise_scales_as_flow_cubed() {
        let u1 = 0.5f32;
        let u2 = 1.0f32;
        let amp1 = dipole_orifice_amplitude(u1);
        let amp2 = dipole_orifice_amplitude(u2);
        assert!(
            (amp2 - 8.0 * amp1).abs() < 1e-4,
            "doubling flow velocity must scale dipole amplitude by 2^3 = 8"
        );
        assert_eq!(dipole_orifice_amplitude(0.0), 0.0);
    }

    #[test]
    fn throttle_area_sweeps_from_leak_to_bore() {
        let bore = 0.070;
        let bore_area = (std::f64::consts::PI * (bore * 0.5) * (bore * 0.5)) as f32;
        let leak_area = bore_area * 0.008;

        let a_shut = throttle_area(bore, 0.0);
        let a_open = throttle_area(bore, 1.0);

        assert!((a_shut - leak_area).abs() < 1e-6);
        assert!((a_open - bore_area).abs() < 1e-6);

        // Monotonic with pedal position
        let mut prev = a_shut;
        for i in 1..=10 {
            let a = throttle_area(bore, i as f32 * 0.1);
            assert!(a >= prev, "throttle area must increase monotonically");
            prev = a;
        }
    }

    #[test]
    fn throttle_restriction_is_passive_and_conserves_continuity() {
        let area = 0.002f32;
        let a_open = area;
        let a_shut = area * 0.008;

        // Wide open throttle: transmission is high, reflection is minimal
        let (refl_open, trans_open) = scatter_throttle_restriction(100.0, 0.0, area, area, a_open);
        assert!(
            (trans_open - 100.0).abs() < 1.0,
            "open throttle must transmit wave: got {trans_open}"
        );
        assert!(
            refl_open.abs() < 1.0,
            "open throttle reflection must vanish: got {refl_open}"
        );

        // Shut throttle: reflection is nearly total rigid (+1.0), transmission is blocked
        let (refl_shut, trans_shut) = scatter_throttle_restriction(100.0, 0.0, area, area, a_shut);
        assert!(
            refl_shut > 90.0,
            "shut throttle must reflect incident wave: got {refl_shut}"
        );
        assert!(
            trans_shut < 10.0,
            "shut throttle must block transmission: got {trans_shut}"
        );

        // Passive: power out <= power in
        let p_in = 100.0 * 100.0 * area;
        let p_out_open = (refl_open * refl_open + trans_open * trans_open) * area;
        let p_out_shut = (refl_shut * refl_shut + trans_shut * trans_shut) * area;
        assert!(p_out_open <= p_in + 1e-3);
        assert!(p_out_shut <= p_in + 1e-3);
    }

    #[test]
    fn closing_the_throttle_attenuates_mouth_output_through_area_term() {
        let system = IntakeSystem::default_for_cylinders(4);
        let mut network_open = IntakeNetwork::new(&system, 4, 48_000.0);
        let mut network_shut = IntakeNetwork::new(&system, 4, 48_000.0);

        network_open.set_throttle(1.0);
        network_shut.set_throttle(0.0);

        let mut energy_open = 0.0f32;
        let mut energy_shut = 0.0f32;

        // Drive with periodic suction rarefaction pulses
        for n in 0..2_400 {
            let excit = if n % 240 == 0 { -5_000.0 } else { 0.0 };
            let excits = [excit, 0.0, 0.0, 0.0];

            let out_open = network_open.step(&excits);
            let out_shut = network_shut.step(&excits);

            energy_open += out_open * out_open;
            energy_shut += out_shut * out_shut;
        }

        let rms_open = (energy_open / 2_400.0).sqrt();
        let rms_shut = (energy_shut / 2_400.0).sqrt();

        assert!(rms_open > 0.0, "open throttle must radiate sound");
        assert!(
            rms_shut < 0.20 * rms_open,
            "shutting the throttle must attenuate mouth output by at least 5x: open={rms_open}, shut={rms_shut}"
        );
    }
}
